// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class AdvertisementConfiguration : IEntityTypeConfiguration<Advertisement>
    {
        public void Configure(EntityTypeBuilder<Advertisement> entity)
        {
            entity.ToTable("Advertisement");

            entity.Property(e => e.AdvertisementSourceBaseId).HasDefaultValueSql("((1))");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Descriptions).HasMaxLength(500);

            entity.Property(e => e.HostName)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.AdvertisementSourceBase)
                .WithMany(p => p.AdvertisementAdvertisementSourceBases)
                .HasForeignKey(d => d.AdvertisementSourceBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Advertisement_BaseValues");

            entity.HasOne(d => d.AdvertisementTypeBase)
                .WithMany(p => p.AdvertisementAdvertisementTypeBases)
                .HasForeignKey(d => d.AdvertisementTypeBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Advertisement_BaseValues1");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.AdvertisementCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdvertismentSource_CreatedBy");

            entity.HasOne(d => d.HeadLineNumberBase)
                .WithMany(p => p.AdvertisementHeadLineNumberBases)
                .HasForeignKey(d => d.HeadLineNumberBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdvertismentSource_HeadLineNumberId");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.AdvertisementModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_AdvertismentSource_ModifiedBy");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.Advertisements)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdvertismentSource_CreatedByRole");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Advertisement> entity);
    }
}
