// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class CommissionConfiguration : IEntityTypeConfiguration<Commission>
    {
        public void Configure(EntityTypeBuilder<Commission> entity)
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Contract)
                .WithMany(p => p.Commissions)
                .HasForeignKey(d => d.ContractId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Commissions_Contracts");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CommissionCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Commissions_Users1");


            entity.HasOne(d => d.Employee)
                .WithMany(p => p.Commissions)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_Commissions_Employees");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.CommissionModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_Commissions_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.Commissions)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Commissions_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Commission> entity);
    }
}
