// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class CommunicationConfiguration : IEntityTypeConfiguration<Communication>
    {
        public void Configure(EntityTypeBuilder<Communication> entity)
        {
            entity.ToTable("Communications");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.SmsUniqueNumber)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.VoipUniqueNumber)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Advertisment)
                .WithMany(p => p.Communications)
                .HasForeignKey(d => d.AdvertismentId)
                .HasConstraintName("FK_Calls_Advertisement");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CommunicationCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Calls_Users1");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.Communications)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Calls_Customers");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.CommunicationModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_Calls_Users");

            entity.HasOne(d => d.Employee)
                .WithMany(p => p.Communications)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_Communications_Employees");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.Communications)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Calls_Roles");

            entity.HasOne(d => d.TypeBase)
                .WithMany(p => p.Communications)
                .HasForeignKey(d => d.TypeBaseId)
                .HasConstraintName("FK_Calls_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Communication> entity);
    }
}
