// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class ContractAttachmentConfiguration : IEntityTypeConfiguration<ContractAttachment>
    {
        public void Configure(EntityTypeBuilder<ContractAttachment> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");


            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Contract)
                .WithMany(p => p.ContractAttachments)
                .HasForeignKey(d => d.ContractId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractAttachments_Contracts");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.ContractAttachmentCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractAttachments_Users1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.ContractAttachmentModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_ContractAttachments_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.ContractAttachments)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractAttachments_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContractAttachment> entity);
    }
}
