// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Domain.Entities.reverse.Configurations
{
    public partial class ContractProjectConfiguration : IEntityTypeConfiguration<ContractProject>
    {
        public void Configure(EntityTypeBuilder<ContractProject> entity)
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Contract)
                .WithMany(p => p.ContractProjects)
                .HasForeignKey(d => d.ContractId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractProjects_Contracts");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.ContractProjectCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractProjects_Users1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.ContractProjectModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_ContractProjects_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.ContractProjects)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractProjects_Roles");

            entity.HasOne(d => d.Project)
                .WithMany(p => p.ContractProjects)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractProjects_Projects");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContractProject> entity);
    }
}
