// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class CountryDivisionConfiguration : IEntityTypeConfiguration<CountryDivision>
    {
        public void Configure(EntityTypeBuilder<CountryDivision> entity)
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.CreatedById).HasDefaultValueSql("((1))");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedById).HasDefaultValueSql("((4))");

            entity.Property(e => e.OwnerRoleId).HasDefaultValueSql("((1))");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.ParentId)
                .IsRequired(false);

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CountryDivisionCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryDivisions2_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.CountryDivisionModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_CountryDivisions2_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.CountryDivisions)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryDivisions2_Roles");

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_CountryDivisions2_CountryDivisions2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CountryDivision> entity);
    }
}
