// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.HasIndex(e => e.Id);

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.EmployeeCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employees_Users1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.EmployeeModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_Employees_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.Employees)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employees_Roles");

            entity.HasOne(d => d.Person)
                .WithOne(p => p.Employee)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.UnitPosition)
                .WithMany(p => p.Employees)
                .HasForeignKey(d => d.UnitPositionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employees_UnitPosition");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
