// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class OperatorConfiguration : IEntityTypeConfiguration<Operator>
    {
        public void Configure(EntityTypeBuilder<Operator> entity)
        {
            entity.HasIndex(e => e.ExtentionNumber);

            entity.HasIndex(e => e.QueueNumber);

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ExtentionNumber)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false); 
            
            entity.Property(e => e.IsActive)
                .IsRequired().HasDefaultValue(true);

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.QueueNumber)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.OperatorCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Operators_Users1");

            entity.HasOne(d => d.Employee)
                .WithOne(p => p.Operator)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Operators_Employees");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.Operators)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_Operators_Roles");

            entity.HasOne(d => d.ModifiedByNavigation)
                .WithMany(p => p.OperatorModifiedByNavigations)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_Operators_Users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Operator> entity);
    }
}
