// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class OutgoingAdvertismentMessageConfiguration : IEntityTypeConfiguration<OutgoingAdvertismentMessage>
    {
        public void Configure(EntityTypeBuilder<OutgoingAdvertismentMessage> entity)
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Reciver)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.AdvertismentSource)
                .WithMany(p => p.OutgoingAdvertismentMessages)
                .HasForeignKey(d => d.AdvertismentSourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SmsHistory_AdvertismentSource");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.OutgoingAdvertismentMessageCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SmsHistory_Users1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.OutgoingAdvertismentMessageModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_SmsHistory_Users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OutgoingAdvertismentMessage> entity);
    }
}
