// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class ProjectConfiguration : IEntityTypeConfiguration<Project>
    {
        public void Configure(EntityTypeBuilder<Project> entity)
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.FilePath).HasMaxLength(500).IsRequired(false);

            entity.Property(e => e.FileUrl).HasMaxLength(500).IsRequired(false);
            entity.Property(e => e.Address).HasMaxLength(500).IsRequired(false);

            entity.Property(e => e.Location).HasColumnType("geometry").IsRequired(false);

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.ProjectCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Projects_Users1");

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Projects_Projects1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.ProjectModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_Projects_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.Projects)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Projects_Roles");

            entity.HasOne(d => d.PriorityBase)
                .WithMany(p => p.Projects)
                .HasForeignKey(d => d.PriorityBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Projects_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Project> entity);
    }
}
