// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class QuestionConfiguration : IEntityTypeConfiguration<Question>
    {
        public void Configure(EntityTypeBuilder<Question> entity)
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.AnswerOptionBaseType)
                .WithMany(p => p.Questions)
                .HasForeignKey(d => d.AnswerOptionBaseTypeId)
                .HasConstraintName("FK_Questions_BaseValueTypes");

            entity.HasOne(d => d.AnswerTypeBase)
                .WithMany(p => p.QuestionAnswerTypeBases)
                .HasForeignKey(d => d.AnswerTypeBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Questions_BaseValues1");

            entity.HasOne(d => d.QuestionTypBase)
                .WithMany(p => p.QuestionQuestionTypBases)
                .HasForeignKey(d => d.QuestionTypBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Questions_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Question> entity);
    }
}
