// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Domain.Entities.reverse.Configurations
{
    public partial class SessionSurveyConfiguration : IEntityTypeConfiguration<SessionSurvey>
    {
        public void Configure(EntityTypeBuilder<SessionSurvey> entity)
        {
            entity.ToTable("SessionSurveys", "dbo");
            entity.Property(e => e.Answer)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.AnswerNavigation)
                .WithMany(p => p.SessionSurveys)
                .HasForeignKey(d => d.AnswerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SessionSurveys_BaseValues1");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.SessionSurveyCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SessionSurveys_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.SessionSurveyModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_SessionSurveys_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.SessionSurveys)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SessionSurveys_Roles");

            entity.HasOne(d => d.Question)
                .WithMany(p => p.SessionSurveys)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SessionSurveys_Questions");

            entity.HasOne(d => d.Task)
                .WithMany(p => p.SessionSurveys)
                .HasForeignKey(d => d.TaskId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SessionSurveys_Tasks");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SessionSurvey> entity);
    }
}
